In [1]:
import numpy as np
import pandas as pd

In [2]:
actual=np.array(["cat","dog","dog","cat","dog","dog","cat"])
predict=np.array(["cat","dog","cat","dog","cat","dog","dog"])

In [5]:
pos="dog"

In [6]:
table=[[0,0],[0,0]]
for i in range(len(actual)):
    if actual[i]!=pos:
        if predict[i]!=pos:
            table[0][0]+=1
        else:
            table[0][1]+=1
    else:
        if predict[i]!=pos:
            table[1][0]+=1
        else:
            table[1][1]+=1
print(table)

[[1, 2], [2, 2]]

In [8]:
x=sum(np.array(table).reshape(-1))
accuracy=(table[0][0]+table[1][1])/x
error=1-accuracy
precision=table[1][1]/sum(table[1])
recall=table[1][1]/(table[0][0]+table[0][1])
specifcity=table[0][0]/(table[0][0]+table[1][0])
f1_score=2*precision*recall/(precision+recall)
print(accuracy,error,precision,error,precision,recall,f1_score)

0.42857142857142855 0.5714285714285714 0.5 0.5714285714285714 0.5 0.6666666666666666 0.5714285714285715

In [11]:
import pandas as pd
df=pd.read_csv("diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [15]:
import numpy as np
import pandas as pd
import seaborn as sns

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [19]:
df=pd.read_csv("diabetes.csv")

In [20]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
# underweigth<18.5
# healthy weight:18.5-24.9
# overweight:25.0-29.9
# obesity>30

In [26]:
df["BMI_CAT"]=pd.cut(df.BMI,bins=[0,18.5,24.9,29.9,100],labels=["UnderWeight","healthy weight","overweight","obesity"])
# Another method is apply