In [1]:
import pandas as pd
import numpy as np

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
df=pd.read_csv("PANDAS_DATA/movies.csv")
df

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [4]:
df.groupby("imdb_rating").agg({"imdb_rating":"max"})

            imdb_rating
                    max   sum
imdb_rating
0.0                 0.0   0.0
1.5                 1.5   3.0
1.7                 1.7   6.8
1.8                 1.8   1.8
1.9                 1.9   5.7
...                 ...   ...
8.6                 8.6   8.6
8.7                 8.7  17.4
8.9                 8.9   8.9
9.0                 9.0   9.0
9.4                 9.4   9.4

[76 rows x 2 columns]

In [10]:
df.groupby("genres")["imdb_rating"].mean().sort_values()

genres
Biography|History          0.0
Drama|Short                0.0
Comedy|Family|Sci-Fi       2.4
Action|Crime|Romance       2.4
Action|Fantasy|Sci-Fi      2.6
                          ...
Adventure|Drama|Musical    8.1
Drama|Short|Thriller       8.2
Drama|Fantasy|Horror       8.2
Documentary|War            8.3
Documentary|Sport          8.6
Name: imdb_rating, Length: 205, dtype: float64

In [13]:
x=df.groupby("genres")["imdb_rating"].mean().sort_values()
#Print movie name with highest imdb in genre

('Action', 78      3.0
176     2.9
367     7.1
368     7.1
435     5.4
452     3.7
535     4.2
538     5.7
637     5.1
1146    5.1
1171    6.3
1310    5.0
1411    3.3
1585    5.0
1627    7.4
Name: imdb_rating, dtype: float64)
('Action|Adventure', 24     5.3
166    4.0
756    4.0
Name: imdb_rating, dtype: float64)
('Action|Adventure|Animation', 685    6.8
706    6.3
903    4.2
Name: imdb_rating, dtype: float64)
('Action|Adventure|Comedy', 13      4.3
203     6.4
314     5.1
321     3.2
537     5.5
598     6.6
789     1.7
1029    5.6
1044    1.7
1067    7.2
1070    4.5
Name: imdb_rating, dtype: float64)
('Action|Adventure|Crime', 928    3.5
Name: imdb_rating, dtype: float64)
('Action|Adventure|Drama', 34      5.7
198     4.1
318     5.7
355     4.6
821     4.6
858     5.4
905     3.4
944     4.8
1009    2.6
1011    3.4
1302    6.0
1330    3.4
1398    5.2
Name: imdb_rating, dtype: float64)
('Action|Adventure|Fantasy', 965     4.6
1026    2.0
1190    3.1
Name: imdb_rating, dtype: float64)
('Action|Adventure|Sci-Fi', 552    5.7
807    4.6
Name: imdb_rating, dtype: float64)
('Action|Adventure|Thriller', 159     6.0
671     5.1
962     3.7
1488    5.3
Name: imdb_rating, dtype: float64)
('Action|Biography|Crime', 105    7.0
220    6.3
294    5.3
668    8.2
Name: imdb_rating, dtype: float64)
('Action|Biography|Drama', 8       6.5
354     8.4
526     6.8
1554    8.1
1581    6.5
Name: imdb_rating, dtype: float64)
('Action|Comedy', 16      7.4
46      4.1
71      3.1
126     4.8
161     3.8
167     6.8
223     6.3
366     5.1
522     4.5
531     5.3
593     1.7
611     4.0
629     6.0
633     4.8
729     4.0
731     4.9
734     5.5
878     6.3
975     4.0
1256    3.5
Name: imdb_rating, dtype: float64)
('Action|Comedy|Crime', 364     4.2
505     4.6
693     8.2
694     8.2
738     5.8
775     7.5
781     3.9
816     2.9
897     4.2
920     4.6
923     3.3
937     4.2
980     5.7
1089    3.3
1108    3.8
1192    3.2
1204    4.6
1436    5.2
1496    6.2
1508    4.2
1608    5.4
Name: imdb_rating, dtype: float64)
('Action|Comedy|Drama', 47      4.2
132     7.2
155     4.1
158     6.3
362     8.0
387     6.0
390     3.3
737     5.6
790     4.9
951     5.9
959     6.1
1111    6.7
1168    7.4
1236    5.3
1253    5.8
1314    7.0
1320    6.9
1381    4.8
1408    4.8
1468    3.3
1523    4.4
1602    4.6
Name: imdb_rating, dtype: float64)
('Action|Comedy|Family', 1446    5.7
Name: imdb_rating, dtype: float64)
('Action|Comedy|Fantasy', 61     3.3
160    4.9
Name: imdb_rating, dtype: float64)
('Action|Comedy|Music', 547    5.1
Name: imdb_rating, dtype: float64)
('Action|Comedy|Musical', 733     5.2
1383    2.4
Name: imdb_rating, dtype: float64)
('Action|Comedy|Mystery', 990    5.3
Name: imdb_rating, dtype: float64)
('Action|Comedy|Romance', 266     4.0
361     5.2
486     5.2
595     5.3
791     4.6
919     6.3
1368    3.9
1509    4.4
Name: imdb_rating, dtype: float64)
('Action|Comedy|Thriller', 201    5.9
Name: imdb_rating, dtype: float64)
('Action|Comedy|War', 409    4.3
Name: imdb_rating, dtype: float64)
('Action|Crime', 1124    7.1
1170    3.2
1418    7.5
1586    5.8
Name: imdb_rating, dtype: float64)
('Action|Crime|Drama', 14      7.5
48      7.0
96      7.4
117     4.3
165     6.8
       ...
1541    4.1
1570    5.3
1579    6.3
1606    4.5
1617    5.3
Name: imdb_rating, Length: 86, dtype: float64)
('Action|Crime|Horror', 1578    5.9
Name: imdb_rating, dtype: float64)
('Action|Crime|Mystery', 958    5.0
Name: imdb_rating, dtype: float64)
('Action|Crime|Romance', 608    2.4
Name: imdb_rating, dtype: float64)
('Action|Crime|Sci-Fi', 399     3.7
1175    2.8
Name: imdb_rating, dtype: float64)
('Action|Crime|Thriller', 38      6.8
215     6.9
384     5.8
575     5.3
580     3.5
683     3.2
732     4.1
774     5.6
832     7.1
886     7.0
1018    4.0
1062    3.4
1129    2.9
1162    6.5
1164    7.2
1207    2.5
1317    6.7
1373    4.2
1603    6.0
Name: imdb_rating, dtype: float64)
('Action|Drama', 41      9.4
56      6.0
66      4.6
112     7.6
228     5.3
263     6.4
458     5.2
468     6.1
493     5.6
523     5.7
590     5.1
659     5.7
661     6.9
751     6.5
783     6.7
1237    3.7
1356    3.7
1391    6.3
1511    6.6
1531    3.7
1536    3.4
1545    6.4
1552    6.0
1562    4.6
1598    4.4
Name: imdb_rating, dtype: float64)
('Action|Drama|Fantasy', 1139    3.8
Name: imdb_rating, dtype: float64)
('Action|Drama|History', 22     7.4
110    7.7
128    5.2
171    5.7
184    5.5
219    8.3
359    5.9
363    7.2
982    7.6
Name: imdb_rating, dtype: float64)
('Action|Drama|Horror', 776    6.2
899    3.2
Name: imdb_rating, dtype: float64)
('Action|Drama|Music', 210    3.4
222    6.2
327    5.0
Name: imdb_rating, dtype: float64)
('Action|Drama|Musical', 356     4.6
434     3.6
1028    2.1
1324    4.6
1453    2.9
Name: imdb_rating, dtype: float64)
('Action|Drama|Mystery', 379     3.3
806     4.4
839     2.7
979     7.3
1224    5.0
1424    3.7
1482    4.7
Name: imdb_rating, dtype: float64)
('Action|Drama|Romance', 39      7.4
55      4.6
295     6.4
342     4.0
371     4.1
457     2.3
556     4.3
628     5.6
682     6.5
861     6.0
873     5.2
995     3.8
1050    7.2
1071    6.3
1121    4.2
1357    4.4
1361    7.9
1394    7.1
1404    4.7
1443    4.1
1455    4.4
1466    2.1
1480    7.1
1502    3.1
1532    5.6
1569    7.2
1577    3.8
Name: imdb_rating, dtype: float64)
('Action|Drama|Sport', 84      8.1
258     7.6
307     7.0
429     6.5
850     6.4
1154    4.5
Name: imdb_rating, dtype: float64)
('Action|Drama|Thriller', 42      7.3
77      7.4
106     7.8
164     7.1
175     7.5
278     7.1
341     6.2
433     5.8
449     7.6
600     6.5
625     7.7
672     5.1
719     6.8
743     3.9
834     6.1
866     5.0
880     6.4
884     5.0
936     4.8
1079    6.1
1229    4.1
1322    7.4
1332    6.0
1607    7.8
Name: imdb_rating, dtype: float64)
('Action|Drama|War', 0       8.4
716     7.2
1039    7.9
1325    4.6
Name: imdb_rating, dtype: float64)
('Action|Fantasy|Sci-Fi', 1379    2.6
Name: imdb_rating, dtype: float64)
('Action|Fantasy|Thriller', 441     5.1
1385    4.4
1525    2.8
Name: imdb_rating, dtype: float64)
('Action|Horror|Sci-Fi', 527    3.1
Name: imdb_rating, dtype: float64)
('Action|Musical|Romance', 1497    6.3
Name: imdb_rating, dtype: float64)
('Action|Mystery|Romance', 179     2.7
1555    5.6
Name: imdb_rating, dtype: float64)
('Action|Mystery|Thriller', 393    7.6
Name: imdb_rating, dtype: float64)
('Action|Romance', 68      3.6
454     2.8
502     5.3
1262    3.6
1462    4.0
1537    3.8
1558    4.3
1560    5.2
1590    4.6
Name: imdb_rating, dtype: float64)
('Action|Romance|Thriller', 700     5.5
1501    3.4
Name: imdb_rating, dtype: float64)
('Action|Sci-Fi', 1186    6.3
Name: imdb_rating, dtype: float64)
('Action|Sci-Fi|Thriller', 857    4.2
934    5.0
Name: imdb_rating, dtype: float64)
('Action|Thriller', 33      4.4
51      5.5
70      0.0
76      5.7
87      5.2
99      5.0
114     2.0
123     5.6
125     4.6
150     3.8
182     6.3
276     6.8
281     5.2
284     5.7
298     0.0
305     5.0
320     5.0
346     6.2
365     8.0
476     5.2
518     7.2
561     3.2
589     8.2
596     6.1
622     7.2
652     5.4
799     6.4
915     6.6
1032    1.5
1243    4.4
1257    5.5
1331    5.2
1351    5.3
1498    6.9
1575    7.1
1593    4.3
Name: imdb_rating, dtype: float64)
('Action|Thriller|War', 169    7.6
Name: imdb_rating, dtype: float64)
('Adventure|Animation|Comedy', 1030    5.2
Name: imdb_rating, dtype: float64)
('Adventure|Animation|Family', 887    5.9
Name: imdb_rating, dtype: float64)
('Adventure|Biography|Drama', 431    8.0
Name: imdb_rating, dtype: float64)
('Adventure|Comedy', 335    7.5
Name: imdb_rating, dtype: float64)
('Adventure|Comedy|Crime', 712     4.2
1074    7.3
Name: imdb_rating, dtype: float64)
('Adventure|Comedy|Drama', 312     5.7
428     3.8
528     5.8
648     5.1
1184    6.8
Name: imdb_rating, dtype: float64)
('Adventure|Drama|Family', 451    6.6
Name: imdb_rating, dtype: float64)
('Adventure|Drama|Musical', 1567    8.1
1568    8.1
Name: imdb_rating, dtype: float64)
('Adventure|Drama|Mystery', 283    6.1
Name: imdb_rating, dtype: float64)
('Adventure|Drama|Thriller', 286     6.7
313     7.5
1430    4.5
Name: imdb_rating, dtype: float64)
('Adventure|Fantasy|Sci-Fi', 333    6.9
Name: imdb_rating, dtype: float64)
('Adventure|Horror|Mystery', 1258    4.6
1423    2.3
Name: imdb_rating, dtype: float64)
('Adventure|Horror|Romance', 840    5.5
Name: imdb_rating, dtype: float64)
('Adventure|Musical|Romance', 1382    4.4
Name: imdb_rating, dtype: float64)
('Adventure|Thriller', 650    7.1
Name: imdb_rating, dtype: float64)
('Animation', 605     6.8
963     7.4
1261    7.3
Name: imdb_rating, dtype: float64)
('Animation|Comedy|Drama', 718    5.7
Name: imdb_rating, dtype: float64)
('Animation|Drama|History', 1228    6.5
Name: imdb_rating, dtype: float64)
('Animation|Drama|Musical', 724    6.5
Name: imdb_rating, dtype: float64)
('Animation|Family|Musical', 574    5.5
Name: imdb_rating, dtype: float64)
('Biography', 336    4.9
Name: imdb_rating, dtype: float64)
('Biography|Crime|Drama', 638    8.3
815    7.2
Name: imdb_rating, dtype: float64)
('Biography|Crime|Thriller', 229    4.2
Name: imdb_rating, dtype: float64)
('Biography|Drama', 2       6.1
9       5.1
31      3.3
40      8.2
62      8.9
116     7.8
135     7.4
254     6.8
270     7.8
293     7.2
374     5.5
430     7.5
494     7.3
496     4.8
817     6.6
1083    7.7
Name: imdb_rating, dtype: float64)
('Biography|Drama|History', 216     8.2
224     6.7
377     5.4
895     7.3
1076    7.3
1275    6.6
1370    7.5
1499    5.0
1550    6.8
1623    6.2
Name: imdb_rating, dtype: float64)
('Biography|Drama|Music', 360    5.5
Name: imdb_rating, dtype: float64)
('Biography|Drama|Romance', 550     7.1
1142    4.1
1211    6.6
Name: imdb_rating, dtype: float64)
('Biography|Drama|Sport', 288    5.8
332    7.7
612    8.2
Name: imdb_rating, dtype: float64)
('Biography|Drama|Thriller', 269    7.7
760    5.6
Name: imdb_rating, dtype: float64)
('Biography|History', 186    0.0
Name: imdb_rating, dtype: float64)
('Comedy', 43      4.8
59      8.2
64      8.1
108     5.2
109     5.6
       ...
1441    4.6
1471    5.4
1475    6.9
1486    5.7
1557    3.7
Name: imdb_rating, Length: 73, dtype: float64)
('Comedy|Crime', 438     7.2
656     6.1
901     2.5
970     5.3
981     5.1
991     5.2
1191    6.7
Name: imdb_rating, dtype: float64)
('Comedy|Crime|Drama', 7       4.3
113     3.7
120     7.0
285     2.9
544     3.5
772     4.0
773     3.8
794     3.7
820     5.3
862     7.1
867     5.6
882     6.0
894     7.5
932     6.8
935     7.3
942     6.2
949     5.1
964     3.0
992     4.2
1015    3.1
1036    7.7
1072    7.0
1160    5.3
1180    8.3
1225    6.6
1489    7.3
1493    7.4
Name: imdb_rating, dtype: float64)
('Comedy|Crime|Family', 413     5.4
1604    4.3
Name: imdb_rating, dtype: float64)
('Comedy|Crime|Mystery', 1073    6.2
1364    6.2
Name: imdb_rating, dtype: float64)
('Comedy|Crime|Romance', 988     4.6
1610    6.0
Name: imdb_rating, dtype: float64)
('Comedy|Crime|Thriller', 533     5.4
609     5.8
1247    5.8
Name: imdb_rating, dtype: float64)
('Comedy|Drama', 6       4.2
63      6.3
72      7.6
97      7.5
121     7.5
       ...
1386    7.4
1459    6.0
1479    3.8
1622    5.7
1626    6.1
Name: imdb_rating, Length: 88, dtype: float64)
('Comedy|Drama|Family', 107     6.4
156     5.7
234     5.7
425     6.2
548     4.7
688     6.4
735     7.8
759     5.5
766     7.8
777     7.4
780     8.0
939     6.4
984     6.3
1006    4.9
1025    1.9
1059    7.6
1114    6.0
1298    6.7
1305    4.4
1309    6.8
1528    4.7
1553    4.6
1576    4.7
1599    4.6
Name: imdb_rating, dtype: float64)
('Comedy|Drama|Fantasy', 178     6.1
309     3.7
439     6.8
485     6.7
567     8.1
714     8.2
841     4.7
844     3.8
856     5.3
900     6.6
1013    3.6
1174    4.1
Name: imdb_rating, dtype: float64)
('Comedy|Drama|Horror', 103    6.2
883    2.9
Name: imdb_rating, dtype: float64)
('Comedy|Drama|Music', 819    4.7
978    7.1
Name: imdb_rating, dtype: float64)
('Comedy|Drama|Musical', 603     7.1
908     5.8
1101    7.1
1119    5.1
1282    6.6
1290    5.9
1316    6.7
1400    4.0
1403    8.1
1415    4.8
1507    4.4
1544    5.0
Name: imdb_rating, dtype: float64)
('Comedy|Drama|Mystery', 372    5.1
Name: imdb_rating, dtype: float64)
('Comedy|Drama|Romance', 54      4.1
79      6.9
115     4.5
145     1.7
148     3.2
       ...
1463    3.3
1529    4.7
1542    5.3
1563    4.8
1571    8.1
Name: imdb_rating, Length: 101, dtype: float64)
('Comedy|Drama|Short', 1478    8.0
Name: imdb_rating, dtype: float64)
('Comedy|Drama|Sport', 802     5.7
956     4.5
1476    2.6
Name: imdb_rating, dtype: float64)
('Comedy|Drama|Thriller', 44      6.0
511     5.5
617     5.3
620     6.7
1017    5.4
1133    6.5
1206    7.2
Name: imdb_rating, dtype: float64)
('Comedy|Family', 152    5.1
879    7.2
Name: imdb_rating, dtype: float64)
('Comedy|Family|Romance', 796     5.8
1306    5.3
Name: imdb_rating, dtype: float64)
('Comedy|Family|Sci-Fi', 703    2.4
Name: imdb_rating, dtype: float64)
('Comedy|Fantasy', 1609    5.3
Name: imdb_rating, dtype: float64)
('Comedy|Fantasy|Romance', 684    5.7
Name: imdb_rating, dtype: float64)
('Comedy|Horror', 127    7.7
334    5.4
478    3.6
Name: imdb_rating, dtype: float64)
('Comedy|Horror|Mystery', 1052    7.2
Name: imdb_rating, dtype: float64)
('Comedy|Music', 1098    7.0
1448    7.2
Name: imdb_rating, dtype: float64)
('Comedy|Musical', 725    5.6
Name: imdb_rating, dtype: float64)
('Comedy|Musical|Mystery', 1615    6.7
Name: imdb_rating, dtype: float64)
('Comedy|Musical|Romance', 665     3.5
1088    3.7
1141    5.2
1198    4.0
1281    3.2
Name: imdb_rating, dtype: float64)
('Comedy|Mystery', 1268    6.1
Name: imdb_rating, dtype: float64)
('Comedy|Mystery|Thriller', 1135    5.6
1150    6.3
Name: imdb_rating, dtype: float64)
('Comedy|Romance', 32      6.6
52      7.5
60      5.7
69      5.8
75      5.7
       ...
1477    6.5
1510    5.0
1535    4.5
1566    4.8
1596    5.8
Name: imdb_rating, Length: 69, dtype: float64)
('Comedy|Romance|Sci-Fi', 911    4.2
Name: imdb_rating, dtype: float64)
('Comedy|Short', 1484    4.4
Name: imdb_rating, dtype: float64)
('Comedy|Sport', 323    4.9
Name: imdb_rating, dtype: float64)
('Comedy|Thriller', 80      6.2
639     6.1
649     2.0
1197    5.4
1342    4.7
Name: imdb_rating, dtype: float64)
('Comedy|War', 655    5.5
Name: imdb_rating, dtype: float64)
('Crime', 516    6.5
Name: imdb_rating, dtype: float64)
('Crime|Drama', 3       6.0
37      8.3
53      8.4
274     5.6
614     6.4
755     7.2
837     8.0
852     6.8
985     6.8
986     6.1
1226    4.8
1406    7.9
1450    6.2
1472    6.9
1504    6.3
1518    6.8
1521    3.3
1574    6.7
1589    7.6
1594    5.1
Name: imdb_rating, dtype: float64)
('Crime|Drama|Musical', 1213    5.7
Name: imdb_rating, dtype: float64)
('Crime|Drama|Mystery', 15      7.9
244     3.7
426     8.2
436     8.2
566     8.1
727     7.2
922     7.4
938     6.4
952     5.2
1019    6.9
1091    7.8
1099    7.7
1113    4.2
1234    4.8
1266    5.5
1303    6.5
1304    5.6
1312    5.4
1343    7.6
1514    6.6
Name: imdb_rating, dtype: float64)
('Crime|Drama|Romance', 57      7.8
465     7.6
998     6.9
1080    2.8
1103    5.3
1434    7.6
Name: imdb_rating, dtype: float64)
('Crime|Drama|Thriller', 93      3.3
140     6.6
221     5.3
233     7.3
301     7.3
316     7.1
349     5.7
488     7.5
557     5.7
578     8.0
793     5.0
830     4.1
835     6.4
904     6.0
930     8.1
941     6.8
948     7.8
974     3.9
1002    6.4
1118    2.9
1131    4.3
1203    4.5
1235    6.8
1363    8.2
Name: imdb_rating, dtype: float64)
('Crime|Musical|Thriller', 480    6.8
Name: imdb_rating, dtype: float64)
('Crime|Mystery', 315    4.7
Name: imdb_rating, dtype: float64)
('Crime|Mystery|Romance', 1042    3.7
Name: imdb_rating, dtype: float64)
('Crime|Mystery|Thriller', 196     5.9
687     7.2
1470    6.9
Name: imdb_rating, dtype: float64)
('Crime|Romance', 542     4.6
1454    3.8
Name: imdb_rating, dtype: float64)
('Crime|Short', 1425    7.6
Name: imdb_rating, dtype: float64)
('Crime|Thriller', 146     8.4
289     6.8
300     5.7
525     6.1
560     4.4
576     6.1
722     3.7
1158    6.3
1410    2.3
1513    3.1
Name: imdb_rating, dtype: float64)
('Documentary', 466     7.5
1435    8.7
1449    7.4
Name: imdb_rating, dtype: float64)
('Documentary|Sport', 192    8.6
Name: imdb_rating, dtype: float64)
('Documentary|War', 1540    8.3
Name: imdb_rating, dtype: float64)
('Drama', 4       7.3
5       7.2
12      5.6
17      7.7
20      6.8
       ...
1595    7.5
1601    7.0
1618    5.5
1624    4.9
1625    3.0
Name: imdb_rating, Length: 162, dtype: float64)
('Drama|Family', 102     6.9
131     7.2
177     5.2
240     6.9
279     8.4
291     6.5
572     7.5
588     6.8
848     4.9
929     6.7
1127    8.4
1308    7.1
1564    5.8
1584    5.0
Name: imdb_rating, dtype: float64)
('Drama|Family|Music', 1048    6.3
Name: imdb_rating, dtype: float64)
('Drama|Family|Musical', 1208    6.6
1270    4.7
1313    7.8
1396    5.3
1505    5.0
Name: imdb_rating, dtype: float64)
('Drama|Family|Mystery', 708    7.2
Name: imdb_rating, dtype: float64)
('Drama|Family|Romance', 49      6.6
241     7.6
460     5.2
1096    5.3
1144    5.4
1414    5.2
1494    6.8
Name: imdb_rating, dtype: float64)
('Drama|Family|Sport', 499     7.4
1066    8.2
Name: imdb_rating, dtype: float64)
('Drama|Family|Thriller', 859    6.0
Name: imdb_rating, dtype: float64)
('Drama|Fantasy', 383    6.6
Name: imdb_rating, dtype: float64)
('Drama|Fantasy|Horror', 143    8.2
Name: imdb_rating, dtype: float64)
('Drama|Fantasy|Mystery', 1469    5.8
Name: imdb_rating, dtype: float64)
('Drama|Fantasy|Romance', 1199    2.2
1288    6.5
1500    4.6
Name: imdb_rating, dtype: float64)
('Drama|Fantasy|Thriller', 1339    4.2
Name: imdb_rating, dtype: float64)
('Drama|History', 50      6.5
256     8.0
933     7.4
1069    8.0
1210    7.0
Name: imdb_rating, dtype: float64)
('Drama|History|Musical', 1263    4.5
1301    5.2
Name: imdb_rating, dtype: float64)
('Drama|History|Romance', 88    7.0
Name: imdb_rating, dtype: float64)
('Drama|History|Sport', 122    7.3
Name: imdb_rating, dtype: float64)
('Drama|History|Thriller', 208    6.0
Name: imdb_rating, dtype: float64)
('Drama|History|War', 492     7.4
498     6.7
779     2.6
1401    5.1
1402    5.1
Name: imdb_rating, dtype: float64)
('Drama|Horror', 1421    6.3
Name: imdb_rating, dtype: float64)
('Drama|Horror|Musical', 1487    6.5
Name: imdb_rating, dtype: float64)
('Drama|Horror|Mystery', 543     2.7
765     4.9
827     3.5
833     4.3
849     3.2
1280    4.3
Name: imdb_rating, dtype: float64)
('Drama|Horror|Romance', 375     4.0
723     4.8
896     4.6
1065    3.8
Name: imdb_rating, dtype: float64)
('Drama|Horror|Thriller', 1081    3.6
Name: imdb_rating, dtype: float64)
('Drama|Music', 11      8.2
217     5.7
238     7.9
345     5.0
966     5.4
1016    7.8
1285    6.9
Name: imdb_rating, dtype: float64)
('Drama|Musical', 532     6.2
1148    6.2
1336    3.1
1461    3.6
1546    5.5
Name: imdb_rating, dtype: float64)
('Drama|Musical|Mystery', 1360    4.6
Name: imdb_rating, dtype: float64)
('Drama|Musical|Romance', 500     6.5
506     4.3
660     6.4
1117    2.4
1120    5.3
1176    6.0
1178    4.7
1269    4.7
1286    7.2
1365    6.2
1369    4.2
1412    5.3
1413    5.3
1420    4.7
1456    4.2
1490    7.6
1515    5.2
1522    3.7
1556    4.6
1559    4.0
1561    6.4
1565    7.4
1572    5.4
1573    4.4
1587    4.5
1591    4.1
1597    4.1
1611    4.0
Name: imdb_rating, dtype: float64)
('Drama|Music|Musical', 343    5.8
591    7.0
808    7.7
Name: imdb_rating, dtype: float64)
('Drama|Music|Romance', 1193    3.5
Name: imdb_rating, dtype: float64)
('Drama|Mystery', 237    6.4
Name: imdb_rating, dtype: float64)
('Drama|Mystery|Romance', 353     4.3
646     1.9
787     5.3
1041    3.9
1053    4.1
1390    3.8
Name: imdb_rating, dtype: float64)
('Drama|Mystery|Thriller', 27      8.0
83      3.8
98      5.7
170     6.2
292     6.9
296     7.2
579     4.9
746     6.1
768     7.2
823     6.9
831     7.0
851     3.4
1000    3.4
1007    5.5

In [ ]:
#PRINT HIGHEST IMDB RATING IN GROUPED GENRE