In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("classwork/IPL_Matches_2008_2022.csv")
df

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [11]:
# df.groupby("Season").agg({"WinningTeam":"max"})
df.groupby("Season")["WinningTeam"].apply(lambda x:x.value_counts().head(1))

Season
2007/08  Rajasthan Royals         13
2009     Delhi Daredevils         10
2009/10  Mumbai Indians           11
2011     Chennai Super Kings      11
2012     Kolkata Knight Riders    12
2013     Mumbai Indians           13
2014     Kings XI Punjab          12
2015     Mumbai Indians           10
2016     Sunrisers Hyderabad      11
2017     Mumbai Indians           12
2018     Chennai Super Kings      11
2019     Mumbai Indians           11
2020/21  Mumbai Indians           11
2021     Chennai Super Kings      11
2022     Gujarat Titans           12
Name: WinningTeam, dtype: int64

In [12]:
df.groupby("WinningTeam")["Player_of_Match"].nunique()

WinningTeam
Chennai Super Kings            39
Deccan Chargers                19
Delhi Capitals                 16
Delhi Daredevils               39
Gujarat Lions                   7
Gujarat Titans                  9
Kings XI Punjab                42
Kochi Tuskers Kerala            4
Kolkata Knight Riders          44
Lucknow Super Giants            6
Mumbai Indians                 43
Pune Warriors                  11
Punjab Kings                   10
Rajasthan Royals               41
Rising Pune Supergiant          7
Rising Pune Supergiants         3
Royal Challengers Bangalore    36
Sunrisers Hyderabad            36
Name: Player_of_Match, dtype: int64

In [22]:
newdf=pd.DataFrame()
newdf["Count"]=df.Venue.value_counts().head()

In [23]:
newdf=newdf.reset_index()
newdf

                                       Venue  Count
0                               Eden Gardens     77
1                           Wankhede Stadium     73
2                      M Chinnaswamy Stadium     65
3                           Feroz Shah Kotla     60
4  Rajiv Gandhi International Stadium, Uppal     49

In [26]:
df1=newdf.merge(df,on="Venue",how="inner")

In [29]:
df1

,Venue,Count,ID,City,Date,Season,MatchNumber,Team1,Team2,TossWinner,...,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,Eden Gardens,77,1178422,Kolkata,2019-04-28,2019,47,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,...,N,Kolkata Knight Riders,Runs,34.0,NaN,AD Russell,"['Shubman Gill', 'CA Lynn', 'AD Russell', 'KD ...","['Q de Kock', 'RG Sharma', 'E Lewis', 'SA Yada...",IJ Gould,Nitin Menon
1,Eden Gardens,77,1178418,Kolkata,2019-04-25,2019,43,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,...,N,Rajasthan Royals,Wickets,3.0,NaN,VR Aaron,"['CA Lynn', 'Shubman Gill', 'N Rana', 'KD Kart...","['AM Rahane', 'SV Samson', 'SPD Smith', 'BA St...",AY Dandekar,IJ Gould
2,Eden Gardens,77,1178410,Kolkata,2019-04-19,2019,35,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,...,N,Royal Challengers Bangalore,Runs,10.0,NaN,V Kohli,"['PA Patel', 'V Kohli', 'AD Nath', 'MM Ali', '...","['CA Lynn', 'SP Narine', 'Shubman Gill', 'RV U...",IJ Gould,Nitin Menon
3,Eden Gardens,77,1178404,Kolkata,2019-04-14,2019,29,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,...,N,Chennai Super Kings,Wickets,5.0,NaN,Imran Tahir,"['CA Lynn', 'SP Narine', 'N Rana', 'RV Uthappa...","['SR Watson', 'F du Plessis', 'SK Raina', 'AT ...",CK Nandan,RJ Tucker
4,Eden Gardens,77,1178401,Kolkata,2019-04-12,2019,26,Kolkata Knight Riders,Delhi Capitals,Delhi Capitals,...,N,Delhi Capitals,Wickets,7.0,NaN,S Dhawan,"['JL Denly', 'Shubman Gill', 'RV Uthappa', 'N ...","['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...",CK Nandan,YC Barde
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,"Rajiv Gandhi International Stadium, Uppal",49,336024,Hyderabad,2008-05-18,2007/08,42,Deccan Chargers,Mumbai Indians,Deccan Chargers,...,N,Mumbai Indians,Runs,25.0,NaN,DJ Bravo,"['AC Gilchrist', 'Shahid Afridi', 'RG Sharma',...","['ST Jayasuriya', 'SR Tendulkar', 'DJ Thornely...",BR Doctrove,DJ Harper
320,"Rajiv Gandhi International Stadium, Uppal",49,336014,Hyderabad,2008-05-11,2007/08,32,Deccan Chargers,Kolkata Knight Riders,Kolkata Knight Riders,...,N,Kolkata Knight Riders,Runs,23.0,NaN,SC Ganguly,"['AC Gilchrist', 'HH Gibbs', 'DB Ravi Teja', '...","['Salman Butt', 'A Chopra', 'SC Ganguly', 'DJ ...",IL Howell,AM Saheba
321,"Rajiv Gandhi International Stadium, Uppal",49,335999,Hyderabad,2008-05-01,2007/08,19,Deccan Chargers,Kings XI Punjab,Kings XI Punjab,...,N,Kings XI Punjab,Wickets,7.0,NaN,SE Marsh,"['AC Gilchrist', 'VVS Laxman', 'HH Gibbs', 'RG...","['SE Marsh', 'RR Sarwan', 'KC Sangakkara', 'Yu...",BR Doctrove,RB Tiffin
322,"Rajiv Gandhi International Stadium, Uppal",49,335990,Hyderabad,2008-04-24,2007/08,9,Deccan Chargers,Rajasthan Royals,Rajasthan Royals,...,N,Rajasthan Royals,Wickets,3.0,NaN,YK Pathan,"['AC Gilchrist', 'VVS Laxman', 'Shahid Afridi'...","['Kamran Akmal', 'GC Smith', 'YK Pathan', 'SR ...",Asad Rauf,MR Benson
323,"Rajiv Gandhi International Stadium, Uppal",49,335988,Hyderabad,2008-04-22,2007/08,7,Deccan Chargers,Delhi Daredevils,Deccan Chargers,...,N,Delhi Daredevils,Wickets,9.0,NaN,V Sehwag,"['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...","['G Gambhir', 'V Sehwag', 'S Dhawan', 'Shoaib ...",IL Howell,AM Saheba

In [35]:
df1.groupby("Venue")["WinningTeam"].value_counts().head(1)

Venue         WinningTeam
Eden Gardens  Kolkata Knight Riders    45
Name: count, dtype: int64

In [34]:
df1.groupby("Venue")["WinningTeam"].apply(lambda x:x.value_counts().head(1))

Venue
Eden Gardens                               Kolkata Knight Riders          45
Feroz Shah Kotla                           Delhi Daredevils               23
M Chinnaswamy Stadium                      Royal Challengers Bangalore    29
Rajiv Gandhi International Stadium, Uppal  Sunrisers Hyderabad            20
Wankhede Stadium                           Mumbai Indians                 42
Name: WinningTeam, dtype: int64

In [40]:
df2=df[df["Season"]=="2022"]

In [41]:
df2

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,1304051,Pune,2022-03-29,2022,5,Rajasthan Royals,Sunrisers Hyderabad,"Maharashtra Cricket Association Stadium, Pune",Sunrisers Hyderabad,field,N,Rajasthan Royals,Runs,61.0,NaN,SV Samson,"['JC Buttler', 'YBK Jaiswal', 'SV Samson', 'D ...","['KS Williamson', 'Abhishek Sharma', 'RA Tripa...",BNJ Oxenford,UV Gandhe
70,1304050,Mumbai,2022-03-28,2022,4,Lucknow Super Giants,Gujarat Titans,"Wankhede Stadium, Mumbai",Gujarat Titans,field,N,Gujarat Titans,Wickets,5.0,NaN,Mohammed Shami,"['KL Rahul', 'Q de Kock', 'E Lewis', 'MK Pande...","['Shubman Gill', 'MS Wade', 'V Shankar', 'HH P...",PG Pathak,VK Sharma
71,1304049,Mumbai,2022-03-27,2022,3,Royal Challengers Bangalore,Punjab Kings,"Dr DY Patil Sports Academy, Mumbai",Punjab Kings,field,N,Punjab Kings,Wickets,5.0,NaN,OF Smith,"['F du Plessis', 'Anuj Rawat', 'V Kohli', 'KD ...","['MA Agarwal', 'S Dhawan', 'PBB Rajapaksa', 'L...",Nitin Menon,YC Barde
72,1304048,Mumbai,2022-03-27,2022,2,Mumbai Indians,Delhi Capitals,"Brabourne Stadium, Mumbai",Delhi Capitals,field,N,Delhi Capitals,Wickets,4.0,NaN,Kuldeep Yadav,"['RG Sharma', 'Ishan Kishan', 'Anmolpreet Sing...","['PP Shaw', 'TL Seifert', 'Mandeep Singh', 'RR...",RJ Tucker,HAS Khalid
73,1304047,Mumbai,2022-03-26,2022,1,Chennai Super Kings,Kolkata Knight Riders,"Wankhede Stadium, Mumbai",Kolkata Knight Riders,field,N,Kolkata Knight Riders,Wickets,6.0,NaN,UT Yadav,"['RD Gaikwad', 'DP Conway', 'RV Uthappa', 'AT ...","['AM Rahane', 'VR Iyer', 'N Rana', 'SS Iyer', ...",AK Chaudhary,Nitin Menon

In [43]:
df3=pd.DataFrame()
df3["Team","Points"]=df2["WinningTeam"].value_counts()
df3

                             (Team, Points)
WinningTeam
Gujarat Titans                           12
Rajasthan Royals                         10
Royal Challengers Bangalore               9
Lucknow Super Giants                      9
Punjab Kings                              7
Delhi Capitals                            7
Sunrisers Hyderabad                       6
Kolkata Knight Riders                     6
Mumbai Indians                            4
Chennai Super Kings                       4

In [ ]:
df2

In [3]:
df.columns

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='str')